import type { GoogleSheetsRow } from "../types.js";

export interface InsertQuery
{
    columns: string[];
    values: string[][];
}

export interface UpdateQuery
{
    table: string;
    assignments: {
        column: string;
        value: string;
    }[];
    where: WhereExpression;
}

export interface DeleteQuery
{
    table: string;
    where: WhereExpression;
}

export interface SelectColumn
{
    tableAlias: string;
    column: string;
    alias: string;
}

export interface FromQuery
{
    table: string;
    alias: string;
}

export type JoinType =
    | 'LEFT'
    | 'INNER';

export type JoinOperand =
    | {
        type: 'column';
        tableAlias: string;
        column: string;
    }
    | {
        type: 'parameter';
        value: string;
    };

export type JoinConditionOperator =
    | '='
    | 'IS NULL'
    | 'IS NOT NULL';

export interface JoinCondition
{
    left: JoinOperand;
    operator: JoinConditionOperator;
    right?: JoinOperand;
}

export interface JoinQuery
{
    type: JoinType;
    table: string;
    alias: string;
    conditions: JoinCondition[];
}

export type JoinedRow = Record<string, GoogleSheetsRow | undefined>;

/**
 * Operators generated by TypeORM FindOperator
 * that can be evaluated by the Google Sheets driver.
 */
export type WhereOperator =
    | '='
    | '!='
    | '<>'
    | '>'
    | '>='
    | '<'
    | '<='
    | 'IS NULL'
    | 'IS NOT NULL'
    | 'IN'
    | 'NOT IN'
    | 'ANY'
    | 'LIKE'
    | 'NOT LIKE'
    | 'ILIKE'
    | 'NOT ILIKE'
    | 'BETWEEN';

export interface WhereCondition
{
    tableAlias: string;
    column: string;
    operator: WhereOperator;
    parameters: string[];
}


export type WhereExpression =
    | {
        type: 'condition';
        condition: WhereCondition;
    }
    | {
        type: 'and';
        expressions: WhereExpression[];
    }
    | {
        type: 'or';
        expressions: WhereExpression[];
    }
    | {
        type: 'not';
        expression: WhereExpression;
    };


export type AggregateFunction =
    | 'COUNT'
    | 'SUM'
    | 'AVG'
    | 'MIN'
    | 'MAX';

export interface AggregateColumn
{
    function: AggregateFunction;
    argument: string;
    alias: string;
}

export type OrderDirection =
    | 'ASC'
    | 'DESC';

export interface OrderBy
{
    tableAlias: string;
    column: string;
    direction: OrderDirection;
}

export interface Pagination
{
    limit?: number;
    offset?: number;
}